### ISSUE TITLE
GPU运算咋调用

### ISSUE THREAD

**Issue by s1010347724j** [WXR1998/taobao_guess_price_2022#10]

**Comment by WXR1998** [comment]
1.需要是N卡；
2.需要装好cuda。装好了的话去pip装一个pytorch-gpu就可以了；

**Comment by s1010347724j** [comment]
![微信图片_20221108143733](https://user-images.githubusercontent.com/54789550/200492495-0a07c777-6e5b-4f8c-95a2-e71080120e43.jpg)
这个乱码是哪里的编码问题呀

**Comment by WXR1998** [comment]
应该是网页编码的问题，网页编码是utf-8，但是存下来的时候用了其他的编码；这个问题你可以修改下ocr.py的68行，把text这个变量重新编码一下试试看能否解决

**Comment by s1010347724j** [comment]
代码小白，怎么改都不对哈哈哈，这个乱码对结果有影响吗

**Comment by WXR1998** [comment]
只是第一列的图看不到，其他没问题

**Comment by s1010347724j** [comment]
我这i7-6700HQ 怎么要17秒才出结果，拖拉机主板都比这跑得快......
