### ISSUE TITLE
手机截图之后，跑提示这个问题

### ISSUE THREAD

**Issue by hungryandfoolishboy** [WXR1998/taobao_guess_price_2022#2]
WARNING:easyocr.easyocr:CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.
Traceback (most recent call last):
  File "C:\Users\Leonardo\Desktop\taobao_guess_price_2022-master\main.py", line 30, in <module>
    sku_list = ocr.get_sku_list(os.path.join(config.input_image_path, input_filename))
  File "C:\Users\Leonardo\Desktop\taobao_guess_price_2022-master\ocr.py", line 39, in get_sku_list
    img = cv2.resize(img, (603, 1304))
cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

**Comment by WXR1998** [comment]
看起来这个是opencv的问题？你输入的图是jpg的吗，如果不是，可能这个就没有成功读入。可以检查看下ocr.py的39行的img它本身的shape是什么

**Comment by hungryandfoolishboy** [comment]
应该是分辨率问题，这个提示 是get sku list,但 sku list 是空的，所以问题是在将图片分割成 sku的问题。

**Comment by hungryandfoolishboy** [comment]
这段代码里面，有针对分辨率微调参数的公式吗？或者说 分辨率越大，哪个值应该越大？
# 将商品图片存到对应的文件夹
    for text, bbox in result:
        x_min = int(bbox[0][0])
        x_max = int(bbox[1][0])
        y_min = int(bbox[0][1])
        y_max = int(bbox[2][1])
        # 此坐标偏移是为了从文字的bbox获取到商品对应图片的bbox，对于不同分辨率的截图需微调此值
        y_min -= 150
        # y_max -= 40
        cropped = img[y_min:y_max, x_min:x_max]
        if cropped.shape[0] * cropped.shape[1] > 0:
            cv2.imwrite(os.path.join(config.sku_image_path, f'{text}.jpg'), cropped)

**Comment by hungryandfoolishboy** [comment]
还有log文件是存在在哪里？

**Comment by hungryandfoolishboy** [comment]
39行 img print 出来时个none

**Comment by hungryandfoolishboy** [comment]
找到问题了，图片名字含有中文
