### ISSUE TITLE
这个脚本有兄弟会跑吗。。。。。。。 跑不起来

### ISSUE THREAD

**Issue by s1010347724j** [WXR1998/taobao_guess_price_2022#3]
这个脚本有兄弟会跑吗。。。。。。。 跑不起来

**Comment by WXR1998** [comment]
有具体报错或者输出吗

**Comment by s1010347724j** [comment]
![微信图片_20221107123016](https://user-images.githubusercontent.com/54789550/200227503-df31dd6b-b10a-4216-adc5-a4701f02333d.png)
 你好，我是py小白，想玩下这个脚本，环境都安装了，输入之后没反应。。

**Comment by WXR1998** [comment]
没有代码基础的话就难了，后面还有不少问题要处理的；
方括号里的东西是可选项，全删了试试先

**Comment by s1010347724j** [comment]
还是没反应 ...

**Comment by s1010347724j** [comment]
都试过

**Comment by s1010347724j** [comment]
兄弟可以私信吗 发您邮箱了 感谢

**Comment by s1010347724j** [comment]
11
