### ISSUE TITLE
我把easyocr替换成了PaddleOCR好像速度快了一点

### ISSUE THREAD

**Issue by WadonLiu** [WXR1998/taobao_guess_price_2022#5]

**Comment by WXR1998** [comment]
nice，我也是写的时候随便找了个成熟的ocr方案，没有太注重速度问题

**Comment by WadonLiu** [comment]
速度差不多，  快是因为我用了2台电脑...

**Comment by WadonLiu** [comment]
from paddleocr import PaddleOCR, draw_ocr
import os
import cv2 as cv2
import logging
import time

import config

def get_sku_list(path: str, prob_thres: float = 0.85):
    """
    从path jpg图像文件中获取所有的商品名，筛选掉置信度较低的文字
    """
    logging.info(f'从文件 {path} 中执行OCR')
    t0 = time.time()
    ocr = PaddleOCR(use_angle_cls=True, lang="ch")
    # decoder = easyocr.Reader(['ch_sim', 'en'])
    img = cv2.imread(path)
    img = cv2.resize(img, (603, 1304))
    # result = decoder.readtext(img)
    result = ocr.ocr(img, cls=True)[0]

    # 筛选概率较高的bbox，筛选长度足够的商品名称
    result = [(_[0], _[1]) for _ in result if _[1][1] > prob_thres]
    result = [(_[0], _[1]) for _ in result if len(_[1][0]) >= 4]

    # 只筛选是商品的文字
    answer_idx = None
    for idx, value in enumerate(result):
        print(value)
        box, (text, prob) = value
        if (prob < prob_thres):
            continue
        print(text)
        if (len(text) < 4):
            continue
        if '晋级' in text or '概率' in text or '总价' in text or '接近' in text or '提交选择' in text:
            answer_idx = idx + 1
            break
    if answer_idx is not None:
        result = result[answer_idx:]
    
    logging.info(f'OCR结果\t{str(result)}')

    # 将商品图片存到对应的文件夹
    for bbox, (text,prob) in result:
        x_min = int(bbox[0][0])
        x_max = int(bbox[1][0])
        y_min = int(bbox[0][1])
        y_max = int(bbox[2][1])
        # 此坐标偏移是为了从文字的bbox获取到商品对应图片的bbox，对于不同分辨率的截图需微调此值
        y_min -= 150
        # y_max -= 40
        # print(x_min, x_max, y_min, y_max)
        cropped = img[y_min:y_max, x_min:x_max]
        if cropped.shape[0] * cropped.shape[1] > 0:
            cv2.imwrite(os.path.join(config.sku_image_path, f'{text}.jpg'), cropped)
    
    # bbox可以舍弃了，只需返回所有的商品名
    result = [_[1][0] for _ in result if not '已选' in _[1][0]]
    t1 = time.time()
    logging.info(f'OCR用时 {t1 - t0:.2f} s')


    return result
    
  依然没通关，搜的价格和商家报的价格有误差,这个好像无解...
