### ISSUE TITLE
有个问题想请求一下

### ISSUE THREAD

**Issue by hungryandfoolishboy** [WXR1998/taobao_guess_price_2022#6]
你是如何去截图发送到代码去跑的？我手机截图 1080*2340可以识别出来。
通过airtest 链接电脑截图得到的， 396*785 无法识别出来或者识别错误。
已经调整了 shape值了。
通过手机截图发到电脑，这就好5~6秒了😂

**Comment by hungryandfoolishboy** [comment]
![20221107180115](https://user-images.githubusercontent.com/14329160/200284255-c4ad664b-ed7b-4e53-b0cc-22403591d071.jpg)
图片样例

**Comment by hungryandfoolishboy** [comment]
通过微信截图出来的。

**Comment by s1010347724j** [comment]
你好兄弟加个好友我告诉你解决方案，你教我跑这个脚本咋样。。。

**Comment by hungryandfoolishboy** [comment]
> 你好兄弟加个好友我告诉你解决方案，你教我跑这个脚本咋样。。。
你这个得翻墙得。

**Comment by hungryandfoolishboy** [comment]
> 你好兄弟加个好友我告诉你解决方案，你教我跑这个脚本咋样。。。

看我发得第一个 issues

**Comment by s1010347724j** [comment]
邮箱加微信1010347724@qq.com

**Comment by s1010347724j** [comment]
邮箱或Q联系把 1010347724

**Comment by zxcvbnm3111** [comment]
有没有视频教程

**Comment by zxcvbnm3111** [comment]
老兄你会了吗

**Comment by WXR1998** [comment]
我直接截图然后微信发送到电脑弄的，没用啥特别的方法

**Comment by zxcvbnm3111** [comment]
> 我直接截图然后微信发送到电脑弄的，没用啥特别的方法

请问怎么运行程序

**Comment by WadonLiu** [comment]
爱思助手实时屏幕截屏，然后把config图片路径设置为爱思助手保存的图片路径，直接运行脚本

**Comment by zxcvbnm3111** [comment]
> 
有视频吗

**Comment by WadonLiu** [comment]
不必纠结，就算能运行，搜的价格和商家报的价格有误差，我用完也没通关...
