### ISSUE TITLE
opencv-python脚本有版本限制吗

### ISSUE THREAD

**Issue by s1010347724j** [WXR1998/taobao_guess_price_2022#7]
opencv-python脚本有版本限制吗

**Comment by s1010347724j** [comment]
![微信图片_20221108004357](https://user-images.githubusercontent.com/54789550/200366193-d38ba73e-ed2d-4f43-b09d-d13f7914d5b6.png)

**Comment by WXR1998** [comment]
我这看是这个
opencv-python-headless==4.5.4.60

**Comment by s1010347724j** [comment]
感谢作者，脚本已经可以正常跑起来了，但是无输出，并且还有一堆报错无头绪。

**Comment by s1010347724j** [comment]
![1](https://user-images.githubusercontent.com/54789550/200394473-b2be986d-248c-4a3b-9b0a-21287d678991.png)
![2](https://user-images.githubusercontent.com/54789550/200394484-273a6dd3-5b21-4e49-989b-7212a8d5b204.png)

**Comment by zxcvbnm3111** [comment]
> ![1](https://user-images.githubusercontent.com/54789550/200394473-b2be986d-248c-4a3b-9b0a-21287d678991.png) ![2](https://user-images.githubusercontent.com/54789550/200394484-273a6dd3-5b21-4e49-989b-7212a8d5b204.png)

怎么运行的

**Comment by s1010347724j** [comment]
作者很有耐心

**Comment by WXR1998** [comment]
这个的原因应该是返回的网页里面有其他编码的文字，但你这个decoder为什么是'latin-1'呢，应该改为utf-8才对。我是在mac下面写的代码，windows要运行可能要specify一下decoder的编码问题
