### ISSUE TITLE
你好，出现AttributeError: module 'parser' has no attribute 'parse'如何解决。。。

### ISSUE THREAD

**Issue by s1010347724j** [WXR1998/taobao_guess_price_2022#9]
![微信图片_20221108111826](https://user-images.githubusercontent.com/54789550/200467934-4af7d824-7c8f-4aba-80c3-c45098956fb4.jpg)

**Comment by WXR1998** [comment]
看起来像是python版本不对，你是python3吗
另外，检查下parser.py是否在根目录下面正确的位置，实在不行就把parser.py改成别的名字，然后把代码里用到的地方都跟着改一下，这个我推测是因为有别的package也是用到了这个parser的名字

**Comment by s1010347724j** [comment]
python3.9，好的我试试

**Comment by WXR1998** [comment]
我更新了一个版本，修复了这个parser名字的问题。你试试看新版本可以了不

> 看起来像是python版本不对，你是python3吗 另外，检查下parser.py是否在根目录下面正确的位置，实在不行就把parser.py改成别的名字，然后把代码里用到的地方都跟着改一下，这个我推测是因为有别的package也是用到了这个parser的名字

**Comment by s1010347724j** [comment]
牛逼牛逼 作者牛逼！！！！！！！！！
